[package]
name = "sh2do"
version = "0.2.0-dev"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
tempfile = "3.24.0"

sh2c = { path = "../sh2c" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
