title: sh2lang
description: A structured shell language
type: docs
theme: minima
header_pages:
  - index.md
  - language.md
  - releases/index.md
  - sh2do.md
plugins:
  - jekyll-sitemap  
url: "https://siu-mak.github.io"
baseurl: "/sh2lang"  
github_username: siu-mak
repository: siu-mak/sh2lang
defaults:
  - scope:
      path: "google796f0b1fd48dd05d.html"
    values:
      sitemap: false
  - scope:
      path: "articles"
    values:
      layout: "sh2_doc"
  - scope:
      path: "tutorials"
    values:
      layout: "sh2_doc"
  - scope:
      path: "releases"
    values:
      layout: "sh2_doc"
  - scope:
      path: "language.md"
    values:
      layout: "sh2_doc"
  - scope:
      path: "sh2do.md"
    values:
      layout: "sh2_doc"
  - scope:
      path: "feature_matrix.md"
    values:
      layout: "sh2_doc"
  - scope:
      path: "codegen-safety.md"
    values:
      layout: "sh2_doc"
  - scope:
      path: "editor_keywords.md"
    values:
      layout: "sh2_doc"
